### ISSUE TITLE
CSS Targets

### ISSUE THREAD

**Issue by Amirk390** [FACN3/umm-el-fahem-2.0#17]
There is some styles that isnt targeting anything

Example

The ***.modal*** style

https://github.com/FACN3/umm-el-fahem-2.0/blob/master/public/style.css#L60-L116

another example is adding ***button--article*** class to the navbar but there is no such class name

https://github.com/FACN3/umm-el-fahem-2.0/blob/master/src/views/partials/navbar.hbs#L11 #

**Comment by hasansaad1** [comment]
modal is targetting the div content on the login page.

**Comment by hasansaad1** [comment]
and button--article is targeting a button that is not displayed yet.
