### ISSUE TITLE
db connection object 

### ISSUE THREAD

**Issue by Karyum** [FACN3/umm-el-fahem-2.0#18]
why do this ? https://github.com/FACN3/umm-el-fahem-2.0/blob/master/database/db_connection.js#L12-L19

why not do what finn did and just use connectionString?

**Comment by hasansaad1** [comment]
well, we forgot how Finn did it, can you tell us how exactly?
@Karyum

**Comment by Karyum** [comment]
@hasansaad1 you remembered apparently
