### ISSUE TITLE
JWT vs cookie signature

### ISSUE THREAD

**Issue by Karyum** [FACN3/umm-el-fahem-2.0#20]
https://github.com/FACN3/umm-el-fahem-2.0/blob/master/src/authentication/cookie.js#L1-L13 here you are using a jwt and a cookie signature, but both do the same job, jwts are used to encrypt/hash cookies

**Comment by hasansaad1** [comment]
cookie signature serves more my needs https://www.npmjs.com/package/cookie-signature
